server:
  port: 5000
  servlet:
    encoding:
      charset: utf-8


logging:
  level:
    '[org.springframework.boot.web]': INFO
  file:
    name: /var/app/current/gameplanner.log


## Swagger 설정
springdoc:
  swagger-ui:
    path: /api-docs.html
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json


