spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  servlet:
    multipart:
      max-file-size: 20MB

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect


jwt:
  header: Authorization
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 86400


## 로그 레벨 설정
logging:
  level:
    '[org.springframework.boot.web]': INFO
    '[org.org.hibernate.SQL]': INFO
    '[org.hibernate.type.descriptor.sql.BasicBinder]': INFO