spring:
  datasource:
    url: jdbc:mysql://gameplanner-rds.ctquk04qya38.ap-northeast-2.rds.amazonaws.com:3306/gameplanner
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: a53440280
  servlet:
    multipart:
      max-file-size: 20MB
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create  # TODO: validate로 변경
      dialect: MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        format_sql: true



