pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main',
                url: "https://github.com/alsduq1117/gameplanner.git",
                credentialsId: 'minyeob'
            }
        }

        stage('Build Project') {
            steps {
                sh 'chmod +x gradlew'
                sh './gradlew clean build'
            }
        }

        stage('Docker Login') {
            steps {
                sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t alsduq1117/jenkins:test .'
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push alsduq1117/jenkins:test'
            }
        }

        stage('Deploy') {
            steps {
                sshPublisher(
                    continueOnError: false, failOnError: true,
                    publishers: [
                        sshPublisherDesc(
                            configName: 'ApplicationServer',
                            transfers: [
                                sshTransfer(
                                    sourceFiles: '$JAR_FILE_PATH,$SCRIPT_FILE_PATH',
                                    removePrefix: '',
                                    remoteDirectory: '/home/ubuntu/app',
                                    execCommand: '''
                                    sudo chmod 777 /home/ubuntu/app/DockerDeploy.sh
                                    sudo chmod 777 /home/ubuntu/app/*.jar
                                    /home/ubuntu/app/DockerDeploy.sh
                                    '''
                                )
                            ]
                        )
                    ]
                )
            }
        }
    }
}